package com.tenma.common.util.sequence;

import com.tenma.common.util.Constants;

/**
 * ss
 * Created by PT TENMA BRIGHT SKY
 * User: sigit
 * Date: 7/11/13
 * Time: 11:25 AM
 */


public interface SEQUENCE_Constants extends Constants {
    String INVOICE_NUMBER_SEQUENCE = "INVM";
    String INVOICE_PRINTED_SEQUENCE = "INPR";
    String BILL_SEQUENCE = "BILL";
    String CLASS_ROOM_SEQUENCE = "CLRM";
    String CUSTOMER_PAYMENT_SEQUENCE = "CSPY";
    String REFUND_PRINTED_SEQUENCE = "REPR";
    String SALES_RECEIPT_SEQUENCE = "SLRC";
    String INVOICE_SUPPLIER_SEQUENCE = "INVS";
    String TERM_OF_PAYMENT_SEQUENCE = "TOPH";
    String REFUND_SUPPLIER_SEQUENCE = "RESP";
    String VOUCHER_TEMPLATE_SEQUENCE = "VHTM";
    String JOURNAL_HEADER_SEQUENCE = "JRHD";
    String ACCOUNT_GROUP_SEQUENCE = "AGSQ";
    String JOURNAL_DETAIL_SEQUENCE = "JRDT";
    String ACCOUNT_CORPORATE_SEQUENCE = "ACCP";
    String ASSET_TYPE_SEQUENCE = "ASTQ";
    String ASSET_CATEGORY_SEQUENCE = "ASCQ";
    String TASK_ACTION_SEQUENCE = "TSAQ";
    String TASK_TYPE_SEQUENCE = "TTYQ";
    String TEMPLATE_HEADER_SEQUENCE = "TMPH";
    String TEMPLATE_DETAIL_SEQUENCE = "TMPD";
    String FIXED_ASSET_SEQUENCE = "FXAS";
    String PETTYCASH_SEQUENCE = "PTCS";
    String RECURRING__HEADER_SEQUENCE = "RCCH";
    String RECURRING_DETAIL_SEQUENCE = "RCCD";
    String ACCOUNT_MASTER_SEQUENCE = "ACCM";
    String ANNOUNCEMENT_SEQUENCE = "ANCM";
    String ACCOUNT_COMMUNITY_SEQUENCE = "ACMT";
    String ADDRESS_BOOK_SEQUENCE = "ADSB";
    String COLLECTION_SEQUENCE = "COLL";
    String PURCHASE_HEADER_SEQUENCE = "PURH";
    String PURCHASE_DETAIL_SEQUENCE = "PURD";
    String TASK_SEQUENCE = "TASK";
    String CLASS_ATTENDANCE_SEQUENCE = "CLAT";
    String COMPLAINT_ACTION_SEQUENCE = "CMAC";
    String COMPLAINT_LOG_SEQUENCE = "CMLG";
    String COMPLAINT_REQUESTED_SEQUENCE = "CMRQ";
    String INVENTORY_SEQUENCE = "INVT";
    String INVENTORY_TRANSACTION_SEQUENCE = "INTS";
    String INVOICE_SEQUENCE = "INVO";
    String INVOICE_ITEM_SEQUENCE = "IVTM";
    String ORDER_SEQUENCE = "ORDR";
    String PARTNER_SEQUENCE = "PTNR";
    String PAYMENT_SEQUENCE = "PYMT";
    String COMMUNITY_SEQUENCE = "COMU";
    String INFO_ITEM_SEQUENCE = "INTM";
    String VOUCHER_SEQUENCE = "VCHR";
    String PMS_EQUIPMENT_MASTER_SEQUENCE = "PMEM";
    String COURSE_CATALOG_SEQUENCE = "CCTG";
    String COURSE_CATALOG_PRICE_SEQUENCE = "CCTP";
    String FRANCHISE_FEE_SEQUENCE = "FFPT";
    String ACADEMY_TYPE_SEQUENCE = "ACAT";
    String ACADEMY_LEVEL_SEQUENCE = "ACLS";
    String STUDENT_IED_SEQUENCE = "SIQC";
    String PROGRAM_SEQUENCE = "PRAS";
    String REG_PAYMENT_SEQUENCE = "REGS";
    String OPEN_CLASS_SCHEDULE = "OCLS";
    String BALANCE_VIEW_GROUP = "BVGP";
    String STUDENT_FED_SEQUENCE = "SFED";
    String GP_SCALE_SEQUENCE = "GSCL";
    String SCHOOL_YEARS_SEQUENCE = "SYSQ";
    String PRINCIPAL_HISTORY_SEQUENCE = "PRHS";
    String EDUCATION_LEVEL_SEQUENCE = "EDLV";
    String FAMILY_RELATION_SEQUENCE = "FMRL";
    String GRADE_FED_SEQUENCE = "GFED";
    String CATALOG_FED_SEQUENCE = "CTLF";
    String PROSPECTIVE_STUDENT_SEQUENCE = "PRSV";
    String ADMISSIONS_CONFIGURATION_SEQUENCE = "ADCS";
    String REPORT_PROFIT_LOSS_SEQUENCE = "RPLS";

    String TEMPORARY_STUDENT_REGISTER_SEQUENCE = "TMSR";

    String UDW_PAYMENT_RECEIPT_NUMBER = "UPRN";
    String COMMUNITY_MEMBER_SEQUENCE = "CMSQ";
    String COMMUNITY_TEMPORARY_MEMBER_SEQUENCE = "CTSQ";
    String COMMUNITY_MANAGEMENT_PERIOD_SEQUENCE = "CMPS";

    String AGENDA_SEQUENCE = "AGES";
    String FORUM_POST_ID = "FRUM";
    String FORUM_TOPIC_ID = "FRTP";


    String COMMUNITY_TIMELINE_SEQUENCE = "CMTL";
    String COMMUNITY_DIRECTORY_SEQUENCE = "CDIR";
    String FILE_REFERENCE_TIMELINE = "FRTL";
    String FILE_REFERENCE_TICKET_SUPPORT = "FRTS";

    String TICKET_SUPPORT_SEQUENCE = "TCSQ";
    String TICKET_SUPPORT_RESPONSE_SEQUENCE = "TCRS";

    String INVITATION_SEQUENCE = "IVTS";

    String TENMA_DEFAULT_EMAIL_SEQUENCE = "TDES";
    String TENMA_DEFAULT_MOBILE_PHONE_SEQUENCE = "TDMS";
    String SYNC_SCHEDULE_SEQUENCE = "SCSS";

    String SYNC_SETTING_HISTORY_SEQUENCE = "SSHS";
    String PRODUCT_CATALOG_SEQUENCE = "PCTS";
    String GROUP_PRODUCT_CATALOG_SEQUENCE = "GPTS";
    String THRESHOLD_ALERT_SEQUENCE = "THSQ";
    String JOB_ASSIGNMENT_SEQUENCE = "JASS";
    String EQUIPMENT_ISA_SEQUENCE = "EQIS";
    String JOB_NUMBER_AUTO_SEQUENCE = "JNAS";
    String JOB_ASSIGNMENT_DETAIL_SEQUENCE = "JASD";
    String PERSONAL_ASSIGNMENT_SEQUENCE = "PASQ";
    String LETTER_OF_COMPLIANCE_SEQUENCE = "LOCS";
    String BS_SUPPORT_REQUEST_SEQUENCE = "BSRS";
    String GS_SUPPORT_REQUEST_SEQUENCE = "GSRS";
    String PROJECT_TEMPORER_AUTO_SEQUENCE = "PTAS";

    String READY_FOR_INVOICE_SEQUENCE = "RFIQ";
    String CASH_PAYMENT_REQUEST_SEQUENCE = "CPRS";
    String CASH_RECEIVED_VOUCHER_SEQUENCE = "CRVS";
    String FINANCE_ADVANCE_SETTLEMENT = "FASS";
    String SALES_PACKAGE_ID = "SPID";
    String BUDGET_GROUP_SEQUENCE = "BGSQ";

    String PROJECT_ID_AUTO_SEQUENCE = "PIAS";
    String CONTRACT_LOCATION_SEQUENCE = "CNTL";
    String PURCHASE_ORDER = "POID";
    String DELIVERY_NOTE_SEQUENCE = "DNID";
    String DELIVERY_NOTE_RETURN_SEQUENCE = "DNRS";
    String SALES_ORDER_SEQUENCES = "SLOS";
    String DELIVERY_ORDER_SEQUENCES = "DLOS";
    String SHIPMENT_ORDER_SEQUENCES = "SHOS";
    String DO_RET_SEQUENCES = "DRTS";
    String RECEIVE_INVPAYMENT_SEQUENCES = "RIPS";
    String MASTER_MENU_SEQUENCE = "MENU";
    String INVENTORY_MOVEMENT_SEQUENCE = "TWIN";
    String EQUIPMENT_NUMBER_SEQUENCE = "EQNS";
    String CASH_ADVANCE_NUMBER_SEQUENCE = "CANS";
    String REPORT_STATUS_REQUIREMENT_SEQUENCE = "RSRS";
    String STOCK_OPNAME_SEQUENCE = "SONS";
    String ITEM_TRANSFER_NUMBER_SEQUENCE = "ITNS";
    String VOUCHER_RETURN_NUMBER_SEQUENCE = "VRNS";
    String REPORT_FINISH_GENERATE_BARCODE = "RFGB";
    String HEADER_PRICING_SEQUENCE = "HPRS";
    String HEADER_FULLDOWN_SEQUENCE = "HFDS";
    String PRODUCTION_CODE_SEQUENCE = "PCOS";
    String KAKI_DO_SEQUENCE = "KDOS";
    String INVOICE_COLLECTION_SEQUEN = "INCS";
    String TRADING_PACKAGE_SEQUENCE = "TPSC";
    String DASHBOARD_SEQUENCE = "DSBS";
    String PAYMENT_HEADER_SEQUENCE = "INVP";
    String UDW_EVENT_SEQUENCE = "UDES";
    String UDW_COST_SEQUENCE = "UCOS";
    String UDW_ROOM_SEQUENCE = "UROS";
    String UDW_STUDENT_PAYMENT_SEQUENCE = "USPS";
    String EDU_CONFIGT_PAYMENT_SEQUENCE = "ECPS";
    String UDW_STUDENT_PAYMENT_DETAILS_SEQUENCE = "USDS";
    String UDW_STAFF_SEQUENCE = "USFS";
    String UDW_TEACHER_SEQUENCE = "UTCS";
    String ACADEMY_SCHEDULE_SEQUENCE = "ACSS";
    String EFLYER_SEQUENCES = "EFLS";
    String ACADEMY_PRIVATE_SEQUENCE = "APTS";
    String ACADEMY_REGULAR_SEQUENCE = "ARGS";
    String ACADEMY_OPEN_SEQUENCE = "AOPS";
    String ACADEMY_GROUP_SEQUENCE = "AGRS";
    String UDW_SUBJECT = "USUB";
    String EFLYER_TRACK_SEQUENCE = "EFTS";
    String PROMO_CLASS_SEQUENCE = "PRCS";
    String ACCOUNT_SETTING_SEQUENCE = "ACST";
    String TYPE_LEAVE_SEQUENCE = "TYLS";
    String UDW_EMPLOYEE_SEQUENCE = "UDES";
    String HOLIDAY_SEQUENCE = "HLDS";
    String NATIONAL_HOLIDAY_SEQUENCE = "NTHS";
    String PAGE_TRACKER_SEQUENCE = "PGTS";
    String COURSE_ID_SEQUENCE = "COIS";
    String QUESTION_ID_SEQUENCE = "QUIS";
    String PROFESSION_ID_SEQUENCE = "PRIS";
    String STUDENT_SIBLING_SEQUENCE = "SSBS";
    String EDU_CURRICULUM_SEQUENCE = "ECRS";
    String EDU_CURRICULUM_DETAIL_SEQUENCE = "ECDS";
    String EDU_CHAPERONE_SEQUENCE = "CPRN";
    String EDU_ASSIGNMENT_SEQUENCE = "EASS";
    String EDU_ASSIGNMENT_DETAIL_SEQUENCE = "EADS";

}